name: pytest
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13' ]
        os: [ ubuntu-latest ]
      fail-fast: false

    name: ${{ matrix.python-version }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: pytest via nox
        run: |
          python -m pip install nox
          python -m nox -s pytest
